/**
 * Generated by @chest-gate/upstream-proxy.
 *
 * Wraps a third-party paid API. The publisher's API key is read from this
 * proxy's own environment — chest gate, the calling agent, and any other
 * party in the request path never see it.
 *
 * Five guarantees enforced per request:
 *   1. Path allowlist — request paths must match an entry in ALLOW_PATHS.
 *   2. Header strip   — the configured headers are dropped from the inbound
 *                       request before forwarding (no smuggled creds).
 *   3. Auth inject    — exactly one upstream auth header, sourced from env.
 *   4. Egress allowlist — only TARGET_ORIGIN is callable; every other host
 *                       is rejected at the request builder.
 *   5. Response sanitisation — set-cookie / www-authenticate stripped from
 *                       upstream responses.
 *
 * Bundled to ../index.js by `npm run bundle`. Vercel ships index.js as-is;
 * src/ is excluded via .vercelignore so Vercel's auto-detection can't try
 * to compile this file in parallel and shadow the bundle.
 */

import { Hono } from "hono";

const TARGET_ORIGIN = "{{TARGET_ORIGIN}}";
const TARGET_PATH_PREFIX = "{{TARGET_PATH}}"; // e.g. "/v3" — appended before forwarded path
const ALLOW_PATHS: string[] = {{ALLOW_PATHS_JSON}};
const STRIP_HEADERS: Set<string> = new Set({{STRIP_HEADERS_JSON}});
const AUTH_HEADER_NAME = {{HEADER_NAME}};
const AUTH_HEADER_VALUE = {{HEADER_VALUE_LITERAL}};

const ALLOW_ALL = ALLOW_PATHS.length === 1 && ALLOW_PATHS[0] === "*";

function pathAllowed(path: string): boolean {
  if (ALLOW_ALL) return true;
  for (const pattern of ALLOW_PATHS) {
    if (pattern === path) return true;
    if (pattern.endsWith("/*")) {
      const prefix = pattern.slice(0, -2);
      if (path.startsWith(prefix)) return true;
    }
    if (pattern.includes("*")) {
      const regex = new RegExp("^" + pattern.replace(/\*/g, "[^/]+") + "$");
      if (regex.test(path)) return true;
    }
  }
  return false;
}

const app = new Hono();

app.get("/__health", (c) => c.json({ ok: true, target: TARGET_ORIGIN }));

app.all("*", async (c) => {
  const url = new URL(c.req.url);
  const incomingPath = url.pathname;

  if (!pathAllowed(incomingPath)) {
    return c.json({ error: "Path not allowed", path: incomingPath }, 403);
  }
  if (!AUTH_HEADER_VALUE) {
    // Don't leak which env var is missing — the README tells the operator.
    return c.json({ error: "Upstream auth not configured" }, 500);
  }

  // Build forwarded headers: strip caller-supplied creds + chest forwarding
  // overhead, preserve content-type and accept, inject our auth.
  const forwardHeaders = new Headers();
  for (const [k, v] of c.req.raw.headers.entries()) {
    if (STRIP_HEADERS.has(k.toLowerCase())) continue;
    forwardHeaders.set(k, v);
  }
  forwardHeaders.set(AUTH_HEADER_NAME, AUTH_HEADER_VALUE);
  // Host header would otherwise advertise the proxy's vanity domain to the
  // upstream — replace with the real target host so virtual-hosted APIs
  // route correctly.
  forwardHeaders.set("host", new URL(TARGET_ORIGIN).host);

  const targetUrl = `${TARGET_ORIGIN}${TARGET_PATH_PREFIX}${incomingPath}${url.search}`;

  // Egress allowlist: defense-in-depth check that the URL we're about to
  // call is the configured target. SSRF would require both the URL builder
  // AND this check to fail.
  if (!targetUrl.startsWith(`${TARGET_ORIGIN}/`) && targetUrl !== TARGET_ORIGIN) {
    return c.json({ error: "Egress blocked" }, 502);
  }

  const init: RequestInit = {
    method: c.req.method,
    headers: forwardHeaders,
    redirect: "manual",
  };
  if (c.req.method !== "GET" && c.req.method !== "HEAD") {
    init.body = c.req.raw.body;
    // @ts-expect-error — `duplex` is required for streaming bodies in Node 20+.
    init.duplex = "half";
  }

  let upstream: Response;
  try {
    upstream = await fetch(targetUrl, init);
  } catch (err) {
    return c.json({ error: "Upstream fetch failed", detail: (err as Error).message }, 502);
  }

  // Sanitise upstream response: drop cookies + auth challenges so we never
  // pass session state up to the agent.
  const responseHeaders = new Headers();
  for (const [k, v] of upstream.headers.entries()) {
    const lower = k.toLowerCase();
    if (lower === "set-cookie" || lower === "www-authenticate") continue;
    responseHeaders.set(k, v);
  }

  return new Response(upstream.body, {
    status: upstream.status,
    statusText: upstream.statusText,
    headers: responseHeaders,
  });
});

export default app;
